cpu:
  peak_threshold_pct: 80.0

ram:
  peak_threshold_pct: 80.0

disk:
  peak_threshold_pct: 80.0

analyzer_workers: 2
hook_workers: 2

storage:
  db_path: "moon.db"

notify:
  - type: telegram
    bot_token: "123456:ABC-DEF"
