cpu:
  peak_threshold_pct: 80.0

ram:
  peak_threshold_pct: 80.0

disk:
  peak_threshold_pct: 80.0

analyzer_workers: 2
hook_workers: 2
collect_interval: 1s

update_repo: "Alice088/moon"

storage:
  db_path: "~/.local/share/moon/moon.db"

notify:
  - type: telegram
    bot_token: "123456:ABC-DEF"
    chat_id: "-1001234567890"
